(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var m,aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},p="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");
},ca=ba(this),q=function(a,b){if(b)a:{var c=ca;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&p(c,a,{configurable:!0,writable:!0,value:b})}};
q("Symbol",function(a){if(a)return a;var b=function(f,l){this.$jscomp$symbol$id_=f;p(this,"description",{configurable:!0,writable:!0,value:l})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",d=0,e=function(f){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(c+(f||"")+"_"+d++,f)};return e},"es6","es3");
q("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=ca[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&p(d.prototype,a,{configurable:!0,writable:!0,value:function(){return da(aa(this))}})}return a},"es6","es3");
var da=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a},r=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}},ea=function(a){if(!(a instanceof Array)){a=r(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a},t=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
q("WeakMap",function(a){function b(){}function c(h){var k=typeof h;return"object"===k&&null!==h||"function"===k}function d(h){if(!t(h,f)){var k=new b;p(h,f,{value:k})}}function e(h){var k=Object[h];k&&(Object[h]=function(n){if(n instanceof b)return n;Object.isExtensible(n)&&d(n);return k(n)})}if(function(){if(!a||!Object.seal)return!1;try{var h=Object.seal({}),k=Object.seal({}),n=new a([[h,2],[k,3]]);if(2!=n.get(h)||3!=n.get(k))return!1;n.delete(h);n.set(k,4);return!n.has(h)&&4==n.get(k)}catch(v){return!1}}())return a;
var f="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var l=0,g=function(h){this.id_=(l+=Math.random()+1).toString();if(h){h=r(h);for(var k;!(k=h.next()).done;)k=k.value,this.set(k[0],k[1])}};g.prototype.set=function(h,k){if(!c(h))throw Error("Invalid WeakMap key");d(h);if(!t(h,f))throw Error("WeakMap key fail: "+h);h[f][this.id_]=k;return this};g.prototype.get=function(h){return c(h)&&t(h,f)?h[f][this.id_]:void 0};g.prototype.has=function(h){return c(h)&&t(h,f)&&t(h[f],
this.id_)};g.prototype.delete=function(h){return c(h)&&t(h,f)&&t(h[f],this.id_)?delete h[f][this.id_]:!1};return g},"es6","es3");
q("Map",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var g=Object.seal({x:4}),h=new a(r([[g,"s"]]));if("s"!=h.get(g)||1!=h.size||h.get({x:4})||h.set({x:4},"t")!=h||2!=h.size)return!1;var k=h.entries(),n=k.next();if(n.done||n.value[0]!=g||"s"!=n.value[1])return!1;n=k.next();return n.done||4!=n.value[0].x||"t"!=n.value[1]||!k.next().done?!1:!0}catch(v){return!1}}())return a;var b=new WeakMap,c=function(g){this.data_={};this.head_=
f();this.size=0;if(g){g=r(g);for(var h;!(h=g.next()).done;)h=h.value,this.set(h[0],h[1])}};c.prototype.set=function(g,h){g=0===g?0:g;var k=d(this,g);k.list||(k.list=this.data_[k.id]=[]);k.entry?k.entry.value=h:(k.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:g,value:h},k.list.push(k.entry),this.head_.previous.next=k.entry,this.head_.previous=k.entry,this.size++);return this};c.prototype.delete=function(g){g=d(this,g);return g.entry&&g.list?(g.list.splice(g.index,1),g.list.length||
delete this.data_[g.id],g.entry.previous.next=g.entry.next,g.entry.next.previous=g.entry.previous,g.entry.head=null,this.size--,!0):!1};c.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=f();this.size=0};c.prototype.has=function(g){return!!d(this,g).entry};c.prototype.get=function(g){return(g=d(this,g).entry)&&g.value};c.prototype.entries=function(){return e(this,function(g){return[g.key,g.value]})};c.prototype.keys=function(){return e(this,function(g){return g.key})};c.prototype.values=
function(){return e(this,function(g){return g.value})};c.prototype.forEach=function(g,h){for(var k=this.entries(),n;!(n=k.next()).done;)n=n.value,g.call(h,n[1],n[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(g,h){var k=h&&typeof h;"object"==k||"function"==k?b.has(h)?k=b.get(h):(k=""+ ++l,b.set(h,k)):k="p_"+h;var n=g.data_[k];if(n&&t(g.data_,k))for(g=0;g<n.length;g++){var v=n[g];if(h!==h&&v.key!==v.key||h===v.key)return{id:k,list:n,index:g,entry:v}}return{id:k,list:n,index:-1,
entry:void 0}},e=function(g,h){var k=g.head_;return da(function(){if(k){for(;k.head!=g.head_;)k=k.previous;for(;k.next!=k.head;)return k=k.next,{done:!1,value:h(k)};k=null}return{done:!0,value:void 0}})},f=function(){var g={};return g.previous=g.next=g.head=g},l=0;return c},"es6","es3");
var fa=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};q("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,f=0;f<e;f++){var l=d[f];if(b.call(c,l,f,d)){b=l;break a}}b=void 0}return b}},"es6","es3");
var u=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};q("Array.prototype.entries",function(a){return a?a:function(){return u(this,function(b,c){return[b,c]})}},"es6","es3");q("Array.prototype.keys",function(a){return a?a:function(){return u(this,function(b){return b})}},"es6","es3");
q("Set",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),d=new a(r([c]));if(!d.has(c)||1!=d.size||d.add(c)!=d||1!=d.size||d.add({x:4})!=d||2!=d.size)return!1;var e=d.entries(),f=e.next();if(f.done||f.value[0]!=c||f.value[1]!=c)return!1;f=e.next();return f.done||f.value[0]==c||4!=f.value[0].x||f.value[1]!=f.value[0]?!1:e.next().done}catch(l){return!1}}())return a;var b=function(c){this.map_=new Map;if(c){c=
r(c);for(var d;!(d=c.next()).done;)this.add(d.value)}this.size=this.map_.size};b.prototype.add=function(c){c=0===c?0:c;this.map_.set(c,c);this.size=this.map_.size;return this};b.prototype.delete=function(c){c=this.map_.delete(c);this.size=this.map_.size;return c};b.prototype.clear=function(){this.map_.clear();this.size=0};b.prototype.has=function(c){return this.map_.has(c)};b.prototype.entries=function(){return this.map_.entries()};b.prototype.values=function(){return this.map_.values()};b.prototype.keys=
b.prototype.values;b.prototype[Symbol.iterator]=b.prototype.values;b.prototype.forEach=function(c,d){var e=this;this.map_.forEach(function(f){return c.call(d,f,f,e)})};return b},"es6","es3");q("Array.prototype.values",function(a){return a?a:function(){return u(this,function(b,c){return c})}},"es8","es3");
q("String.prototype.repeat",function(a){return a?a:function(b){var c=fa(this,null,"repeat");if(0>b||1342177279<b)throw new RangeError("Invalid count value");b|=0;for(var d="";b;)if(b&1&&(d+=c),b>>>=1)c+=c;return d}},"es6","es3");q("String.prototype.padStart",function(a){return a?a:function(b,c){var d=fa(this,null,"padStart");b-=d.length;c=void 0!==c?String(c):" ";return(0<b&&c?c.repeat(Math.ceil(b/c.length)).substring(0,b):"")+d}},"es8","es3");
var w=this||self,x=function(a,b,c,d){a=a.split(".");d=d||w;a[0]in d||"undefined"==typeof d.execScript||d.execScript("var "+a[0]);for(var e;a.length&&(e=a.shift());)if(a.length||void 0===b)d=d[e]&&d[e]!==Object.prototype[e]?d[e]:d[e]={};else if(!c&&ha(b)&&ha(d[e]))for(var f in b)b.hasOwnProperty(f)&&(d[e][f]=b[f]);else d[e]=b},ha=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},ia=function(a,b){function c(){}c.prototype=b.prototype;a.superClass_=b.prototype;a.prototype=new c;a.prototype.constructor=
a;a.base=function(d,e,f){for(var l=Array(arguments.length-2),g=2;g<arguments.length;g++)l[g-2]=arguments[g];return b.prototype[e].apply(d,l)}},y=function(a){return a};function z(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,z);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));void 0!==b&&(this.cause=b);this.reportErrorToServer=!0}ia(z,Error);z.prototype.name="CustomError";function A(a,b){for(var c=a.split("%s"),d="",e=c.length-1,f=0;f<e;f++)d+=c[f]+(f<b.length?b[f]:"%s");z.call(this,d+c[e]);this.messagePattern=a}ia(A,z);A.prototype.name="AssertionError";var ja=function(a,b){throw new A("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var B;var ka={},C=function(a,b){this.privateDoNotAccessOrElseSafeHtmlWrappedValue_=b===ka?a:"";this.implementsGoogStringTypedString=!0};C.prototype.getTypedStringValue=function(){return this.privateDoNotAccessOrElseSafeHtmlWrappedValue_.toString()};C.prototype.toString=function(){return this.privateDoNotAccessOrElseSafeHtmlWrappedValue_.toString()};
var D=function(a){if(a instanceof C&&a.constructor===C)return a.privateDoNotAccessOrElseSafeHtmlWrappedValue_;var b=typeof a;ja("expected object of type SafeHtml, got '"+a+"' of type "+("object"!=b?b:a?Array.isArray(a)?"array":b:"null"));return"type_error:SafeHtml"},E=function(a){if(void 0===B){var b=null;var c=w.trustedTypes;if(c&&c.createPolicy)try{b=c.createPolicy("goog#html",{createHTML:y,createScript:y,createScriptURL:y})}catch(d){w.console&&w.console.error(d.message)}B=b}a=(b=B)?b.createHTML(a):
a;return new C(a,ka)};var F=function(a,b){this.name=a;this.value=b};F.prototype.toString=function(){return this.name};var G=new F("OFF",Infinity),la=new F("WARNING",900),ma=new F("CONFIG",700),na=function(a){this.capacity_="number"===typeof a?a:0;this.clear()},H;m=na.prototype;
m.addRecord=function(a,b,c){if(!this.isBufferingEnabled())return new I(a,b,c);var d=(this.curIndex_+1)%this.capacity_;this.curIndex_=d;if(this.isFull_)return d=this.buffer_[d],d.reset(a,b,c),d;this.isFull_=d==this.capacity_-1;return this.buffer_[d]=new I(a,b,c)};m.forEachRecord=function(a){var b=this.buffer_;if(b[0]){var c=this.curIndex_,d=this.isFull_?c:-1;do d=(d+1)%this.capacity_,a(b[d]);while(d!==c)}};m.isBufferingEnabled=function(){return 0<this.capacity_};m.isFull=function(){return this.isFull_};
m.clear=function(){this.buffer_=Array(this.capacity_);this.curIndex_=-1;this.isFull_=!1};var I=function(a,b,c,d,e){this.exception_=void 0;this.reset(a||G,b,c,d,e)};m=I.prototype;m.reset=function(a,b,c,d,e){this.time_=d||Date.now();this.level_=a;this.msg_=b;this.loggerName_=c;this.exception_=void 0;this.sequenceNumber_="number"===typeof e?e:oa};m.getLoggerName=function(){return this.loggerName_};m.setLoggerName=function(a){this.loggerName_=a};m.getException=function(){return this.exception_};
m.setException=function(a){this.exception_=a};m.getLevel=function(){return this.level_};m.setLevel=function(a){this.level_=a};m.getMessage=function(){return this.msg_};m.setMessage=function(a){this.msg_=a};m.getMillis=function(){return this.time_};m.setMillis=function(a){this.time_=a};m.getSequenceNumber=function(){return this.sequenceNumber_};var oa=0,J=function(a,b){this.level=null;this.handlers=[];this.parent=(void 0===b?null:b)||null;this.children=[];this.logger={getName:function(){return a}}};
J.prototype.getEffectiveLevel=function(){if(this.level)return this.level;if(this.parent)return this.parent.getEffectiveLevel();ja("Root logger has no level set.");return G};J.prototype.publish=function(a){for(var b=this;b;)b.handlers.forEach(function(c){c(a)}),b=b.parent};var K=function(){this.entries={};var a=new J("");a.level=ma;this.entries[""]=a},L;
K.prototype.getLogRegistryEntry=function(a,b){var c=this.entries[a];if(c)return void 0!==b&&(c.level=b),c;c=this.getLogRegistryEntry(a.slice(0,Math.max(a.lastIndexOf("."),0)));var d=new J(a,c);this.entries[a]=d;c.children.push(d);void 0!==b&&(d.level=b);return d};K.prototype.getAllLoggers=function(){var a=this;return Object.keys(this.entries).map(function(b){return a.entries[b].logger})};var M=function(){L||(L=new K);return L};/*

 SPDX-License-Identifier: Apache-2.0
*/
function N(a){return{valueOf:a}.valueOf()};var pa=N(function(){try{return new URL("s://g"),!0}catch(a){return!1}}),qa=["data:","http:","https:","mailto:","ftp:"],ra=[],sa=function(a){var b=M().getLogRegistryEntry("safevalues",void 0).logger;if(b){var c=la;a="A URL with content '"+a+"' was sanitized away.";var d;if(d=b)if(d=b&&c){d=c.value;var e=b?M().getLogRegistryEntry(b.getName()).getEffectiveLevel():G;d=d>=e.value}d&&(c=c||G,d=M().getLogRegistryEntry(b.getName()),"function"===typeof a&&(a=a()),H||(H=new na(0)),b=H.addRecord(c,a,b.getName()),
b.setException(void 0),d.publish(b))}};-1===ra.indexOf(sa)&&ra.push(sa);var O={};function ta(a){var b=document.createElement("template");if(!("content"in b)){b=E("<html><body>"+a);b=(new DOMParser).parseFromString(D(b),"text/html");for(a=b.createDocumentFragment();0<b.body.childNodes.length;)a.appendChild(b.body.firstChild);return a}a=E(a);if(void 0!==b.tagName){if("script"===b.tagName.toLowerCase())throw Error("Use safeScriptEl.setTextContent with a SafeScript.");if("style"===b.tagName.toLowerCase())throw Error("Use safeStyleEl.setTextContent with a SafeStyleSheet.");}b.innerHTML=
D(a);return b.content};function ua(a){a=a.nodeName;return"string"===typeof a?a:"FORM"}function va(a){a=a.nodeType;return a===Node.ELEMENT_NODE||"number"!==typeof a};var P=function(a,b,c,d,e){this.allowedElements=a;this.elementPolicies=b;this.allowedGlobalAttributes=c;this.globalAttributePolicies=d;this.globallyAllowedAttributePrefixes=e};P.prototype.isAllowedElement=function(a){return"form"!==a.toLowerCase()&&(this.allowedElements.has(a)||this.elementPolicies.has(a))};
P.prototype.getAttributePolicy=function(a,b){b=this.elementPolicies.get(b);return(null==b?0:b.has(a))?b.get(a):this.allowedGlobalAttributes.has(a)?{policyAction:1}:(b=this.globalAttributePolicies.get(a))?b:this.globallyAllowedAttributePrefixes&&[].concat(ea(this.globallyAllowedAttributePrefixes)).some(function(c){return 0===a.indexOf(c)})?{policyAction:1}:{policyAction:0}};var Q="ARTICLE SECTION NAV ASIDE H1 H2 H3 H4 H5 H6 HEADER FOOTER ADDRESS P HR PRE BLOCKQUOTE OL UL LH LI DL DT DD FIGURE FIGCAPTION MAIN DIV EM STRONG SMALL S CITE Q DFN ABBR RUBY RB RT RTC RP DATA TIME CODE VAR SAMP KBD SUB SUP I B U MARK BDI BDO SPAN BR WBR INS DEL PICTURE PARAM TRACK MAP TABLE CAPTION COLGROUP COL TBODY THEAD TFOOT TR TD TH SELECT DATALIST OPTGROUP OPTION OUTPUT PROGRESS METER FIELDSET LEGEND DETAILS SUMMARY MENU DIALOG SLOT CANVAS FONT CENTER".split(" "),R=[["A",new Map([["href",
{policyAction:2}]])],["AREA",new Map([["href",{policyAction:2}]])],["LINK",new Map([["href",{policyAction:2,conditions:new Map([["rel",new Set("alternate author bookmark canonical cite help icon license next prefetch dns-prefetch prerender preconnect preload prev search subresource".split(" "))]])}]])],["SOURCE",new Map([["src",{policyAction:2}]])],["IMG",new Map([["src",{policyAction:2}]])],["VIDEO",new Map([["src",{policyAction:2}]])],["AUDIO",new Map([["src",{policyAction:2}]])]],S="title aria-atomic aria-autocomplete aria-busy aria-checked aria-current aria-disabled aria-dropeffect aria-expanded aria-haspopup aria-hidden aria-invalid aria-label aria-level aria-live aria-multiline aria-multiselectable aria-orientation aria-posinset aria-pressed aria-readonly aria-relevant aria-required aria-selected aria-setsize aria-sort aria-valuemax aria-valuemin aria-valuenow aria-valuetext alt align autocapitalize autocomplete autocorrect autofocus autoplay bgcolor border cellpadding cellspacing checked color cols colspan controls datetime disabled download draggable enctype face formenctype frameborder height hreflang hidden ismap label lang loop max maxlength media minlength min multiple muted nonce open placeholder preload rel required reversed role rows rowspan selected shape size sizes slot span spellcheck start step summary translate type valign value width wrap itemscope itemtype itemid itemprop itemref".split(" "),
T=[["dir",{policyAction:3,conditions:N(function(){return new Map([["dir",new Set(["auto","ltr","rtl"])]])})}],["async",{policyAction:3,conditions:N(function(){return new Map([["async",new Set(["async"])]])})}],["cite",{policyAction:2}],["loading",{policyAction:3,conditions:N(function(){return new Map([["loading",new Set(["eager","lazy"])]])})}],["poster",{policyAction:2}],["target",{policyAction:3,conditions:N(function(){return new Map([["target",new Set(["_self","_blank"])]])})}]],wa=new P(new Set(Q),
new Map(R),new Set(S),new Map(T)),xa=new P(new Set(Q),new Map(R),new Set(N(function(){return S.concat(["class","id"])})),new Map(N(function(){return T.concat([["style",{policyAction:4}]])}))),ya=new P(new Set(N(function(){return Q.concat("STYLE TITLE INPUT TEXTAREA BUTTON LABEL".split(" "))})),new Map(R),new Set(N(function(){return S.concat(["class","id","tabindex","contenteditable","name"])})),new Map(N(function(){return T.concat([["style",{policyAction:4}]])})),new Set(["data-","aria-"]));var U=function(a,b){this.sanitizerTable=a;this.changes=[];if(b!==O)throw Error("Bad secret");};m=U.prototype;m.sanitizeAssertUnchanged=function(a){this.changes=[];var b=this.sanitize(a);if(0!==this.changes.length)throw Error('Unexpected change to HTML value as a result of sanitization. Input: "'+(a+'", sanitized output: "'+b+'"\nList of changes:')+this.changes.join("\n"));return b};
m.sanitize=function(a){var b=document.createElement("span");b.appendChild(this.sanitizeToFragment(a));a=(new XMLSerializer).serializeToString(b);a=a.slice(a.indexOf(">")+1,a.lastIndexOf("</"));return E(a)};
m.sanitizeToFragment=function(a){var b=this;a=ta(a);a=document.createTreeWalker(a,NodeFilter.SHOW_ELEMENT|NodeFilter.SHOW_TEXT,function(l){return b.nodeFilter(l)},!1);for(var c=a.nextNode(),d=document.createDocumentFragment(),e=d;null!==c;){var f=void 0;if(c.nodeType===Node.TEXT_NODE)f=this.sanitizeTextNode(c);else if(va(c))f=this.sanitizeElementNode(c);else throw a="",a="Node is not of type text or element",Error(a);e.appendChild(f);if(c=a.firstChild())e=f;else for(;!(c=a.nextSibling())&&(c=a.parentNode());)e=
e.parentNode}return d};m.sanitizeTextNode=function(a){return document.createTextNode(a.data)};
m.sanitizeElementNode=function(a){var b=ua(a),c=document.createElement(b);a=a.attributes;for(var d=r(a),e=d.next();!e.done;e=d.next()){var f=e.value;e=f.name;f=f.value;var l=this.sanitizerTable.getAttributePolicy(e,b);if(this.satisfiesAllConditions(l.conditions,a))switch(l.policyAction){case 1:c.setAttribute(e,f);break;case 2:a:if(l=void 0,pa){try{l=new URL(f)}catch(g){l="https:";break a}l=l.protocol}else b:{l=document.createElement("a");try{l.href=f}catch(g){l=void 0;break b}l=l.protocol;l=":"===
l||""===l?"https:":l}l=void 0!==l&&-1!==qa.indexOf(l.toLowerCase())?f:"about:invalid#zClosurez";l!==f&&this.recordChange("Url in attribute "+e+' was modified during sanitization. Original url:"'+f+'" was sanitized to: "'+l+'"');c.setAttribute(e,l);break;case 3:c.setAttribute(e,f.toLowerCase());break;case 4:c.setAttribute(e,f);break;case 0:this.recordChange("Attribute: "+e+" was dropped");break;default:throw Error("Unhandled AttributePolicyAction case");}else this.recordChange("Not all conditions satisfied for attribute: "+
e+".")}return c};m.nodeFilter=function(a){if(a.nodeType===Node.TEXT_NODE)return NodeFilter.FILTER_ACCEPT;if(!va(a))return NodeFilter.FILTER_REJECT;var b=ua(a);if(null===b)return this.recordChange("Node name was null for node: "+a),NodeFilter.FILTER_REJECT;if(this.sanitizerTable.isAllowedElement(b))return NodeFilter.FILTER_ACCEPT;this.recordChange("Element: "+b+" was dropped");return NodeFilter.FILTER_REJECT};m.recordChange=function(a){this.changes.push(a)};
m.satisfiesAllConditions=function(a,b){if(!a)return!0;a=r(a);for(var c=a.next();!c.done;c=a.next()){var d=r(c.value);c=d.next().value;d=d.next().value;var e=void 0;if((c=null==(e=b.getNamedItem(c))?void 0:e.value)&&!d.has(c))return!1}return!0};var za=N(function(){return new U(wa,O)}),Aa=N(function(){return new U(xa,O)}),Ba=N(function(){return new U(ya,O)});var Ca={0:1,1:.01},Da={0:.1,1:.01};function Ea(a,b){try{Ba.sanitizeAssertUnchanged(a)}catch(c){return/([.]corp[.]google[.]com|[.]proxy[.]googleprod[.]com|[.]googlers[.]com)$/.test(window.location.hostname)&&c instanceof Error?V(b,"H_SLSANITIZE",c.message):V(b,"H_SLSANITIZE"),!0}try{Aa.sanitizeAssertUnchanged(a)}catch(c){return V(b,"H_RSANITIZE"),!0}try{za.sanitizeAssertUnchanged(a)}catch(c){return V(b,"H_SANITIZE"),!0}return!1}
function V(a,b,c){(Fa?Fa:"undefined"!==typeof window&&window.navigator&&void 0!==window.navigator.sendBeacon?navigator.sendBeacon.bind(navigator):Ga)("https://csp.withgoogle.com/csp/lcreport/"+a.reportingId,JSON.stringify({host:window.location.hostname,type:b,additionalData:c}))}function Ga(a,b){var c=new XMLHttpRequest;c.open("POST",a);c.setRequestHeader("Content-Type","application/json");c.send(b)}var Fa;var W=function(a,b){this.lodash_=a;this.timeout_=b};W.prototype.copyWidgetData=function(a){a=a||[];this.copyToClipboard_(this.parseWidgetData_(a))};W.prototype.parseWidgetData_=function(a){var b=a[1].values,c=[];c.push(a[0].value);b.forEach(function(d,e){return c.push(e+1+") "+d)});return c};
W.prototype.copyToClipboard_=function(a){var b=a.join("\r\n"),c=document.createElement("div");c.textContent=b;c.style.opacity="0";document.body.appendChild(c);var d=document.createRange();d.selectNode(c);window.getSelection().removeAllRanges();window.getSelection().addRange(d);var e=function(f){document.removeEventListener("copy",e);void 0!==f.clipboardData&&(f.clipboardData.setData("text/plain",b),f.clipboardData.setData("text/html",a.join("<br>")),f.preventDefault())};document.addEventListener("copy",
e);document.execCommand("copy");c.remove();this.onCopyNotify_()};W.prototype.onCopyNotify_=function(){if(0===document.getElementsByClassName("copy-notification").length){var a=document.createElement("div");a.textContent=document.getElementsByClassName("translate-patch")[0].textContent;a.className="copy-notification";document.body.appendChild(a);this.timeout_(this.lodash_.bind(function(){a.remove()},a),2E3)}};x("$jscomp$scope$1445061910$0$ClipboardService",W,!0,void 0);W.$inject=["lodash","$timeout"];var X=function(){this.oldTypeToNewTypeDictionary_={TIMESERIES_GRAPH_AVERAGES_CHART:"TIMESERIES",TIMESERIES_GRAPH_0:"TIMESERIES",GEO_TABLE:"GEO_MAP",TOP_ENTITIES:"RELATED_TOPICS",TOP_QUERIES:"RELATED_QUERIES",RISING_QUERIES:"RELATED_QUERIES",GEO_MAP:"GEO_MAP"}};m=X.prototype;m.convertDateWithHours_=function(a,b){var c=a.match(b);b=c[1];a=parseInt(c[2],10);c=c[4];var d=new Date(b);d.setHours(a);b=new Date(b);b.setHours(parseInt(a,10)+parseInt(c,10));return""+this.dateTimeStringFormat_(d)+(" "+this.dateTimeStringFormat_(b))};
m.dateStringFormat_=function(a){return""+a.getFullYear()+("-"+(a.getMonth()+1).toString().padStart(2,"0"))+("-"+a.getDate().toString().padStart(2,"0"))};m.convertDateWithMonth_=function(a,b){a=a.match(b);b=parseInt(a[1],10);var c=parseInt(a[2],10),d=new Date(c,b-1,1);c=new Date(c,b-1,1);c.setMonth(b+parseInt(a[3],10)-1,0);return""+this.dateStringFormat_(d)+(" "+this.dateStringFormat_(c))};
m.dateTimeStringFormat_=function(a){return this.dateStringFormat_(a)+("T"+a.getHours().toString().padStart(2,"0"))};
m.convertOldEmbedParams=function(a){var b=this,c={};if(0===Object.keys(a).length)return null;var d;a.geo&&(d=a.geo.replace(/(\w+,?)\s?/g,"$1"));var e=a.date?a.date.split(",").map(function(k){return b.convertDateParam_(k)}).join(","):"all";a.cat&&(c.cat=a.cat.replace(/(.*-)?(\d+)$/,"$2"));c.comparisonItems={};var f=[];a.q&&a.q.split(",").forEach(function(k){f.push({keyword:k,geo:d||"",time:e})},this);var l=a.cid||"",g="",h=l.match(/(^\w*)[_](\d)[_]\d/);h&&0<h.length&&(l=h[1],0!=h[2]&&(g="_"+h[2]));
l=this.oldTypeToNewTypeDictionary_[l]+g;c.q=a.q;c.widgetType=l;c.comparisonItems.comparisonItem=f;c.comparisonItems.category=c.cat||0;c.comparisonItems.property=a.gprop||"";return c};m.convertDateParam_=function(a){if(""===a)return"all";a=a.replace(/\+/g," ");if(/now|today/.test(a))return a;var b=null,c=/(\d{1,2})\/(\d{4}) (\d*)M/i,d=/(\d{4}-\d{2}-\d{2})T(\d{2})([\d\\:]*) (\d+)H/i;c.test(a)?b=this.convertDateWithMonth_(a,c):d.test(a)&&(b=this.convertDateWithHours_(a,d));return b};
x("$jscomp$scope$1847708173$0$OldFeCompatibilityUtil",X,!0,void 0);var Y,Ha=new X,Z=function(a,b,c){c||(c={});c.guestPath||(c.guestPath="https://trends.google.com/trends/embed/");this.url_=a||"";this.params_=b||{};this.config_=c},Ia=function(a,b,c){return new Z(b?a+"/"+b:a,{},c)},Ja=function(a,b,c){return new Z("yis/"+c+"/"+(b.geo||"GLOBAL")+"/"+a,{},b)},Ka=function(a,b,c){return new Z("explore/"+a,{req:b,tz:(new Date).getTimezoneOffset()},c)};m=Z.prototype;m.createIframe_=function(a){var b=document.createElement("iframe"),c;for(c in a)b.setAttribute(c,a[c]);return b};
m.createIframeCycle_=function(a,b){var c=this;this.socketHandshake_(a,b,function(d){d.data.isReady&&(a.style.borderRadius="2px",a.style.boxShadow="0px 0px 2px 0px rgba(0,0,0,0.12), 0px 2px 2px 0px rgba(0,0,0,0.24)");d.data.height&&(a.style.height=d.data.height+"px",d.data.isIeAndLineChart&&c.setMobilePreviewLineChartWidthInIe_())})};
m.setMobilePreviewLineChartWidthInIe_=function(){var a=document.getElementsByTagName("embed-widget-preview")[0];0!==a.length&&"false"!==a.getAttribute("force-mobile-mode")&&(a=a.find("iframe"))&&(a=a.contentDocument.getElementsByClassName("fe-line-chart"),0!==a.length&&a[0].setAttribute("width",this.IFRAME_WIDTH_+"px"))};
m.generate_=function(){if(!/^(https?:\/\/)?([a-z0-9\.]+)?(\.google\.com)?/i.test(this.config_.guestPath)&&/^[^.]+\.[a-z]{2,4}\/?/i.test(this.config_.guestPath))console.error("Iframe caller domain name not allowed!");else if(this.config_.width&&!/^\d{1,4}(px|%)?$/i.test(this.config_.width))console.error("Width parameter contain illegal value!");else{var a=this.config_.guestPath+this.url_,b=[],c="trends-widget-"+this.generateSeed_(),d;for(d in this.params_)Object.prototype.hasOwnProperty.call(this.params_,
d)&&b.push(d+"="+encodeURIComponent(JSON.stringify(this.params_[d])));this.config_.timeStamp&&b.push("ts="+this.config_.timeStamp);void 0!==this.config_.forceMobileMode&&b.push("forceMobileMode="+!!this.config_.forceMobileMode);void 0!==this.config_.isPreviewMode&&b.push("isPreviewMode="+!!this.config_.isPreviewMode);this.config_.exploreQuery&&b.push("eq="+encodeURIComponent(this.config_.exploreQuery));this.config_.locale&&b.push("hl="+this.config_.locale.replace(/[^a-z]/ig,""));this.config_.geo&&
b.push("geo="+this.config_.geo);b.length&&(a+="?"+b.join("&"));a=this.createIframe_({id:c,title:c,src:a,width:this.config_.width||"100%",frameBorder:0,scrolling:0});return{id:c,element:a}}};m.generateSeed_=function(){return Y?++Y:Y=1};
m.render=function(){var a=this.generate_();if(a){var b=a.element.outerHTML;b=null===b?"null":void 0===b?"undefined":b;if("string"!==typeof b)throw Error("Expected a string");var c={reportingId:"1b698618-3907-4b70-b0dc-dd0de9a64184"},d;if(d=c){var e,f;d=Math.random()<(null!=(f=null!=(e=c.samplingRate)?e:Ca[c.reportingId[0]])?f:0)}if(d&&"DocumentFragment"in window){var l,g;Math.random()<(null!=(g=null!=(l=c.heartbeatRate)?l:Da[c.reportingId[0]])?g:0)&&V(c,"HEARTBEAT");Ea(b,c)||(e=void 0,e=void 0===
e?{}:e,f=b.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&apos;"),e.preserveSpaces&&(f=f.replace(/(^|[\r\n\t ]) /g,"$1&#160;")),e.preserveNewlines&&(f=f.replace(/(\r\n|\n|\r)/g,"<br>")),e.preserveTabs&&(f=f.replace(/(\t+)/g,'<span style="white-space:pre">$1</span>')),E(f).toString()!==b&&V(c,"H_ESCAPE"))}b=E(b);document.write(D(b));b=document.getElementById(a.id);this.createIframeCycle_(b,a.id)}return b};
m.renderTo=function(a){var b=this.generate_();if(b){var c=b.element;a.appendChild(c);this.createIframeCycle_(c,b.id)}return c};m.socketHandshake_=function(a,b,c){a.addEventListener("load",function(){a.contentWindow.postMessage({uniqueID:b},"*")});window.addEventListener("message",function(d){d.data.uniqueID===b&&c(d)},!1)};x("trends.embed.renderWidget",function(a,b,c){return(new Ia(a,b,c)).render()},!0,void 0);
x("trends.embed.renderTopChartsWidget",function(a,b,c){return(new Ja(a,b,c)).render()},!0,void 0);x("trends.embed.renderWidgetTo",function(a,b,c,d){return(new Ia(b,c,d)).renderTo(a)},!0,void 0);x("trends.embed.renderTopChartsWidgetTo",function(a,b,c,d){return(new Ja(b,c,d)).renderTo(a)},!0,void 0);var La=function(a,b,c){return(new Ka(a,b,c)).render()};x("trends.embed.renderExploreWidget",La,!0,void 0);x("trends.embed.renderExploreWidgetTo",function(a,b,c,d){return(new Ka(b,c,d)).renderTo(a)},!0,void 0);
x("trends.embed.renderExploreWidgetFromOldParamaters",function(a){a=Ma(a);var b=Ha.convertOldEmbedParams(a),c="";a.cat&&(c=a.cat.split("-"),c="&cat="+c[c.length-1]);La(b.widgetType,b.comparisonItems,{exploreQuery:"date="+b.comparisonItems.comparisonItem[0].time+"&q="+b.q+(a.geo?"&geo="+a.geo:"")+(a.gprop?"&gprop="+a.gprop:"")+c},{exploreQuery:"q="+b.q+"&date="+b.comparisonItems.comparisonItem[0].time,guestPath:"https://trends.google.com/trends/"})},!0,void 0);
var Ma=function(a){var b={};a.replace(/[?&](.+?)=([^&#]*)/g,function(c,d,e){b[d]=decodeURI(e).replace(/\+/g," ")});return b};}).call(this);
